services:
  sqlite_base:
    build: .
    container_name: sqlite_base
    volumes:
      - ./DATA:/app/DATA
      - ./SRC:/app/SRC
    command: tail -f /dev/null

  csv-to-sqlite:
    build: .
    depends_on:
      - sqlite_base
    volumes:
      - ./DATA:/app/DATA
      - ./SRC:/app/SRC
    command: python SRC/script.py
